import showNumber from "helpers/input/showNumber"

const FA_TEXT = {
    input: {
        phoneIsNotValid: "شماره موبایل وارد شده معتبر نمی‌باشد",
        emailIsNotValid: "ایمیل وارد شده معتبر نمی‌باشد",
        urlIsNotValid: "لینک وارد شده معتبر نمی‌باشد",
        priceIsNotValid: `مبلغ وارد شده باید حداقل ${showNumber(1000)} تومان باشد`,
        minLengthErr: (name: string, min: number) => `${name} باید حداقل شامل ${min} کاراکتر باشد.`,
    },
    login: "ورود",
    remainedToCode: "مانده تا دریافت مجدد کد",
    codeAgain: "دریافت مجدد کد",
    loginDesc: "ورود شما به معنای پذیرش شرایط بنیاد علوی و قوانین حریم خصوصی است",
    loginSignup: "ورود | ثبت‌نام",
    enterPhone: "سلام!\nلطفا شماره موبایل خود را وارد کنید",
    enterCode: "کد تایید را وارد کنید",
    codeSent: (phone: string) => `کد تایید برای شماره ${phone} پیامک شد`,
    allCats: "همه دسته‌ها",
    projectChances: "فرصت‌های مهربانی",
    projectChances2: "فرصت‌های نیکوکاری",
    projectSimilarChances2: "فرصت‌های مشابه نیکوکاری",
    aboutUs: "درباره ما",
    logout: "خروج از حساب کاربری",
    logoutDesc: "آیا می‌خواهید از حساب کاربری خود خارج شوید؟",
    exit: "خروج",
    cancel: "انصراف",
    contactUs: "ارتباط با ما",
    showAll: "مشاهده همه",
    progressFund: (funded_amount: number, required_amount: number) => `${showNumber(funded_amount)} از ${showNumber(required_amount)} تومان`,
    fundGot: " تامین شده",
    categories: "دسته‌بندی‌ها",
    footerTxt: "تمامی حقوق مادی و معنوی این سایت متعلق به بنیاد خیریه علوی  می‌باشد.",
    contactUsFooter: "راه‌‌های ارتباطی",
    descProject: "توضیحات پروژه",
    province: (province: string = "تهران") => `استان ${province}`,
    county: (county: string = "تهران") => `شهرستان ${county}`,
    involve: "مشارکت در پروژه",
    peopleCount: (count: number) => `${count} نفر`,
    involvedPeopleCount: ` در این طرح مشارکت کرده‌اند.`,
    inputPrice: "مبلغ مورد نظرتان را وارد کنید:",
    inputPriceHolder: "مبلغ مورد نظر",
    toman: "تومان",
    pay: "پرداخت",
    home: "خانه",
    projectChance: "فرصت مهربانی",
    profile: "پروفایل",
    noProjectFound: "پروژه‌ای یافت نشد.",
    user: "کاربر",
    account: "حساب کاربری",
    helpHistory: "تاریخچه کمک‌ها",
    name: "نام",
    lastName: "نام خانوادگی",
    submit: "تایید",
}

export default FA_TEXT
